### ISSUE TITLE
[Feed-watcher][v0.0.1]Failed to install the app.

### ISSUE THREAD

**Issue by 44asad** [zouroboros/podcast-watcher#20]
### Actual Behaviour
The application Failed to install in my device.
### Expected Behaviour

I expected that i can install and use the applicatiom successfully.
### How to Reproduce
* Download the app from release page
* click the app to install
* see the error
### Information
App version:v0.0.1
Os:Android 5.0.1
Device:Samsung j2
### Recording of the bug

https://youtu.be/_a4Ta61LC4Y

**Comment by zouroboros** [comment]
Thanks for taking your time and creating this issue. But the problem here is that you are using a android version that is too old (5.0.1). FeedWatcher needs at least android 6.0.

**Comment by 44asad** [comment]
ok sir!
