### ISSUE TITLE
Feeds do not load - Samsung Galaxy S21

### ISSUE THREAD

**Issue by rogerm4242** [zouroboros/podcast-watcher#42]
Toronto ATOM feed link: https://weather.gc.ca/rss/battleboard/on61_e.xml
Webpage where I got the link: https://weather.gc.ca/warnings/report_e.html?on61

When trying to load any of the weather alert feeds from Environment Canada, FeedWatcher displays the error "Loading failed" and the "Subscribe" button is greyed out.

**Comment by rogerm4242** [comment]
Sorry, I cannot get any feeds to load. I get the same error.

Edit: installed from F-Droid.

**Comment by zouroboros** [comment]
I added a fix for the Environment Canada feed. Could you provide the URLs of other feeds that you can not add? That would be really helpful.

Anyways thank you very very much for taking the time and opening this issue.

**Comment by zouroboros** [comment]
The fix is included in the new 0.0.19-alpha version.

**Comment by rogerm4242** [comment]
Thanks for the update! I will test as soon as Fdroid builds the new version.

**Comment by rogerm4242** [comment]
Environment Canada feeds now are loading correctly for me also, as well as every other feed I tried. Thanks for the fix!
