### ISSUE TITLE
Shorter scan interval

### ISSUE THREAD

**Issue by rogerm4242** [zouroboros/podcast-watcher#43]
I have been testing FeedWatcher with Environment Canada weather alert feeds. When checking for severe weather warnings, it would be nice to set the scan interval down to 15 minutes or 30 minutes instead of an hour. 

Environment Canada can easily change their weather alerts feed more frequently than 15 minutes when there are severe thunderstorm or tornado warnings happening.

**Comment by zouroboros** [comment]
I implemented shorter scan intervals (down to 15min). Please keep in mind that android does not guarantee that a interval will be kept and that the minimal scan interval can vary between devices. The preferences screen will show you your device limits. I hope this will help you.
