### ISSUE TITLE
Cannot import Atom Feed via URL

### ISSUE THREAD

**Issue by theAkito** [zouroboros/podcast-watcher#44]
Was trying to import [this feed](https://gitlab.com/fdroid/fdroiddata/-/commits/master?feed_token=MVWauMqepiSMCUyvjLif&format=atom), but it did not work, crashing the App.

To be sure, the feed was not faulty itself, I successfully imported it into another feed reader from F-Droid via URL and it worked fine, instantly.

**Comment by zouroboros** [comment]
Thank you very much for your bug report the fix will land in the next version.
